import type { SiteDictionary } from "@/lib/types";

const fr: SiteDictionary = {
  meta: {
    title: "Technologie. Digital. Leadership.",
    description:
      "Portfolio de Paul Kombetto : ingénieur en systèmes embarqués et IoT, en évolution vers le digital, le marketing et le leadership. Construire, connecter, faire avancer.",
  },
  nav: {
    brand: "Paul Kombetto",
    exploreLabel: "Explorer",
    exploreTitle: "Une personne. Plusieurs dimensions.",
    exploreIntro: "Trois espaces, trois façons de me découvrir plus en profondeur.",
    exploreLinks: [
      {
        index: "01",
        label: "AI & IoT",
        keyword: "Construire",
        description: "Systèmes connectés et intelligents.",
        href: "/ai-iot",
        variant: "ai",
      },
      {
        index: "02",
        label: "Digital Marketing",
        keyword: "Connecter",
        description: "Stratégie, contenu et développement commercial.",
        href: "/marketing",
        variant: "marketing",
      },
      {
        index: "03",
        label: "Leadership & Volunteering",
        keyword: "Faire avancer",
        description: "Communication, communauté et engagement.",
        href: "/leadership",
        variant: "leadership",
      },
    ],
    contactLabel: "Contact",
    closeLabel: "Fermer",
    languageLabel: "Langue",
  },
  profile: {
    name: "Paul Kombetto",
    location: "Cotonou, Bénin",
    email: "paulkombetto1@gmail.com",
    phone: "+229 01 63 42 04 44",
    linkedin: "Paul KOMBETTO",
    linkedinUrl: "https://www.linkedin.com/in/paul-kombetto",
  },
  home: {
    hero: {
      eyebrow: "Portfolio personnel",
      name: "Paul Kombetto",
      signature: "Technologie. Digital. Leadership.",
      headline: "Je construis mon parcours à l'intersection de la technologie, du digital et de l'humain.",
      media: { alt: "Portrait de Paul Kombetto", label: "Hero — portrait professionnel" },
      ctas: [
        { label: "Découvrir mon parcours", href: "#story" },
        { label: "Me contacter", href: "#contact" },
      ],
      soundLabel: "Son",
      soundPlayingLabel: "En lecture",
      scrollCue: "Faire défiler",
    },
    intro: {
      text: "Formé aux systèmes embarqués et à l'IoT, j'ai progressivement élargi mon terrain d'action vers le digital, le développement de projets, la communication et le leadership. Aujourd'hui, je cherche à comprendre les problèmes dans leur ensemble, construire des solutions utiles et contribuer à faire avancer les personnes et les projets qui les portent.",
      media: { alt: "Paul Kombetto dans son environnement de travail", label: "Intro — parcours / environnement de travail" },
    },
    story: {
      eyebrow: "My story",
      title: "Je n'ai jamais voulu me limiter à une seule dimension.",
      paragraphs: [
        "Ma curiosité m'a d'abord conduit vers la technologie. À l'université, les systèmes embarqués et l'IoT m'ont appris à regarder ce qui se passe derrière les applications : les capteurs, les microcontrôleurs, les données, le code et les contraintes du monde réel.",
        "Mais en avançant, j'ai compris qu'une bonne technologie ne suffit pas. Il faut aussi comprendre le problème que l'on cherche à résoudre, les personnes concernées, leur contexte et la manière dont une solution peut réellement être adoptée.",
        "C'est ce qui m'a progressivement amené vers le digital, le marketing, le business development, le CRM, la gestion de projets et le leadership.",
      ],
      emphasis: "Construire des solutions. Comprendre les enjeux. Travailler avec les autres. Et apprendre à transformer les idées en actions.",
      media: { alt: "Photo liée au parcours de Paul Kombetto", label: "Story — photo liée au parcours" },
      imageSide: "right",
    },
    whatIDo: {
      title: "Different fields. One way of thinking.",
      intro: "Mes expériences peuvent sembler différentes au premier regard. Pourtant, elles reposent sur une même approche : comprendre, structurer, construire et faire évoluer.",
      dimensions: [
        {
          key: "ai-iot",
          keyword: "Construire",
          title: "AI & IoT",
          text: "Je conçois et expérimente des systèmes connectés et intelligents, à la croisée de l'embarqué, de l'IoT, de l'automatisation et de l'IA.",
          href: "/ai-iot",
          media: { alt: "Systèmes connectés et intelligents", label: "AI & IoT card" },
        },
        {
          key: "marketing",
          keyword: "Connecter",
          title: "Digital Marketing",
          text: "Je travaille sur la manière dont les produits, services et entreprises expliquent leur valeur, atteignent leur public et transforment leur présence digitale en actions concrètes.",
          href: "/marketing",
          media: { alt: "Stratégie digitale et marketing", label: "Marketing card" },
        },
        {
          key: "leadership",
          keyword: "Faire avancer",
          title: "Leadership & Volunteering",
          text: "Je m'intéresse à la communication, à la coordination, à la prise de responsabilité et aux initiatives qui permettent aux personnes et aux projets d'avancer ensemble.",
          href: "/leadership",
          media: { alt: "Leadership et engagement communautaire", label: "Leadership card" },
        },
      ],
    },
    selectedWork: {
      title: "Quelques projets qui racontent mon parcours.",
      items: [
        {
          tag: "AI × IoT × Embedded Systems",
          title: "Smart Automated Greenhouse",
          description: "Prototype de serre connectée permettant de surveiller l'environnement et d'automatiser certaines actions.",
          href: "/ai-iot/projects/automated-greenhouse",
          cta: "Voir le projet",
          media: { alt: "Prototype de serre automatisée", label: "Project cover — greenhouse" },
        },
        {
          tag: "Marketing × Digital × Business",
          title: "Digital Strategy & Commercial Development",
          description: "Travail autour de la stratégie de contenu, du CRM, de la prospection et du développement commercial.",
          href: "/marketing/case-studies/from-content-to-commercial-action",
          cta: "Voir l'expérience",
          media: { alt: "Stratégie digitale et développement commercial", label: "Marketing work" },
        },
        {
          tag: "Leadership × Communication × Volunteering",
          title: "Leadership & Community",
          description: "Expériences de prise de parole, de modération, de coordination et d'engagement communautaire.",
          href: "/leadership",
          cta: "Découvrir",
          media: { alt: "Engagement communautaire et leadership", label: "Leadership / event" },
        },
      ],
    },
    experience: {
      title: "Learning by doing.",
      entries: [
        {
          organization: "KAWA Services",
          role: "Growth Management Intern",
          period: "Juillet 2026 — Présent",
          tags: ["Digital Marketing", "Commercial Development", "Digital Solutions"],
          description: "Une expérience où j'ai travaillé à la croisée du marketing, du commercial et des solutions digitales, avec des responsabilités allant de la stratégie de contenu à la prospection, au CRM et à la structuration d'actions commerciales.",
          media: { alt: "Environnement de travail chez KAWA Services", label: "KAWA — environnement / campagne / solution" },
        },
        {
          organization: "Tout-Talent",
          role: "AI & Tech Applied Growth Intern",
          period: "Mars — Juin 2025",
          tags: ["Data", "Growth", "Communication technique"],
          description: "Analyse des données utilisateurs et produit pour identifier des opportunités de croissance et d'engagement, en traduisant des solutions techniques en termes compréhensibles pour des parties prenantes non techniques.",
          media: { alt: "Environnement de travail chez Tout-Talent", label: "Tout-Talent — environnement de travail" },
        },
        {
          organization: "Benin Excellence",
          role: "Embedded Systems and AI Intern",
          period: "Juillet — Août 2024",
          tags: ["Arduino", "Python", "Machine Learning"],
          description: "Prototypage de systèmes embarqués avec Arduino et Python, du câblage aux tests fonctionnels, et implémentation d'algorithmes de machine learning pour résoudre des problèmes d'ingénierie appliquée.",
          media: { alt: "Prototypage de systèmes embarqués", label: "Benin Excellence — projet technique" },
        },
        {
          organization: "IFRI / Université d'Abomey-Calavi",
          role: "Bachelor of Science — Systèmes embarqués & IoT",
          period: "2022 — 2025",
          tags: ["Microcontrôleurs", "RTOS", "IoT & protocoles sans fil"],
          description: "Une formation qui m'a donné une base en systèmes embarqués, programmation, électronique, IoT et conception de solutions. Moyenne : 15.21/20.",
          media: { alt: "Université d'Abomey-Calavi, IFRI-UAC", label: "Université / projet technique" },
        },
      ],
    },
    leadershipImpact: {
      title: "Beyond professional titles.",
      paragraphs: [
        "Certaines expériences ne tiennent pas dans une ligne de CV.",
        "Modérer une discussion, prendre la parole, coordonner une activité, lancer une initiative ou accepter une responsabilité : ce sont aussi des situations qui construisent une manière de travailler avec les autres.",
        "Ces expériences ont progressivement façonné ma manière de communiquer, de prendre des initiatives et de créer un environnement où les autres peuvent également contribuer.",
      ],
      media: { alt: "Leadership et communauté", label: "Leadership / community" },
      imageSide: "left",
    },
    whatsNext: {
      title: "Where I'm going.",
      paragraphs: [
        "Mon parcours évolue vers un point de rencontre entre technologie, management et transformation digitale.",
        "Je veux continuer à comprendre la technologie, mais aussi les organisations, les personnes et les enjeux qui permettent à un projet technologique de créer une vraie valeur.",
        "À terme, je souhaite contribuer à la conception, au pilotage et à la transformation de projets technologiques avec un impact concret.",
      ],
      signature: "Technology × Management × Impact.",
      media: { alt: "Vision et perspectives futures", label: "Future / vision" },
      imageSide: "right",
    },
    contact: {
      title: "Construisons quelque chose d'utile.",
      text: "Une idée, un projet, une collaboration ou simplement une conversation intéressante : je suis toujours ouvert à découvrir de nouvelles opportunités.",
      media: { alt: "Paul Kombetto — contact", label: "Contact — portrait discret" },
      emailLabel: "Email",
      phoneLabel: "Téléphone",
      locationLabel: "Localisation",
      linkedinLabel: "LinkedIn",
      resumeLabel: "Télécharger mon CV",
    },
  },
  aiIot: {
    hero: {
      eyebrow: "AI & IoT",
      title: "AI & IoT",
      subtitle: "From connected devices to intelligent systems.",
      text: "Mon parcours technique commence par une question simple : comment utiliser la technologie pour observer, comprendre et agir sur le monde réel ?",
      media: { alt: "Systèmes connectés et intelligents", label: "Hero AI & IoT" },
    },
    technicalStory: {
      title: "Un fil conducteur : percevoir, analyser, agir.",
      paragraphs: [
        "Les systèmes embarqués m'ont appris à regarder le monde physique derrière les applications : capteurs, microcontrôleurs, énergie, communication, données et contraintes matérielles.",
        "L'IoT m'a ensuite permis de relier ce monde physique au monde numérique.",
        "Puis une autre question est apparue : que faire de toutes ces données ? C'est là que mon intérêt pour l'IA et les systèmes intelligents s'est développé.",
      ],
      emphasis: "Je m'intéresse ainsi aux systèmes capables de percevoir, analyser et agir.",
      media: { alt: "Parcours technique de Paul Kombetto", label: "Technical journey / diagram" },
      imageSide: "right",
    },
    stats: [
      { label: "Formation", value: "BSc Systèmes embarqués & IoT" },
      { label: "Langages", value: "Python · C/C++ · Java" },
      { label: "Terrain", value: "Arduino · ESP32 · Computer Vision" },
    ],
    projectsTitle: "Projects",
    projectsIntro: "Chaque projet technique est présenté comme une histoire : contexte, problème, concept, architecture et résultats.",
    projects: [
      {
        slug: "automated-greenhouse",
        title: "Automated Greenhouse — IoT + AI",
        subtitle: "Smart Automated Greenhouse System",
        category: "AI × IoT × Embedded Systems",
        summary: "Prototype de serre connectée permettant de surveiller l'environnement et d'automatiser certaines actions.",
        coverMedia: { alt: "Prototype de serre automatisée", label: "Project cover" },
        context: "Dans une serre, la température, l'humidité, la lumière et l'humidité du sol peuvent évoluer rapidement. Une surveillance manuelle peut demander du temps et retarder certaines décisions.",
        problem: "Comment surveiller l'environnement d'une serre et déclencher automatiquement certaines actions à partir des données collectées ?",
        concept: "Créer un prototype de serre connectée capable de collecter des données environnementales et de déclencher des actions automatisées. Ce projet, réalisé comme thèse de fin d'études à l'IFRI-UAC, est motivé par le fait d'avoir grandi dans une famille agricole — appliquer l'IoT à faible coût à l'agriculture smallholder.",
        architectureSteps: ["Sensors", "ESP32", "Data Collection", "Decision / Automation", "Actuators", "Monitoring Interface"],
        hardware: ["ESP32", "DHT11", "Soil Moisture Sensor", "LDR", "Relays"],
        software: ["Programmation ESP32 (C/C++)", "Blynk IoT", "Logique d'automatisation", "Collecte et visualisation des données"],
        role: "Conception du système, intégration des composants, programmation, connexion à la plateforme IoT et automatisation — en tant que seul concepteur du projet, de bout en bout.",
        learnings: [
          "Un système IoT n'est pas seulement un ensemble de composants connectés.",
          "Il faut penser toute la chaîne : acquisition, communication, traitement, décision et action.",
        ],
        futureImprovements: [
          "Amélioration de l'automatisation",
          "Analyse avancée des données",
          "Ajout d'algorithmes d'IA",
          "Prédiction",
          "Optimisation énergétique",
          "Amélioration de l'architecture",
        ],
        gallery: [
          { alt: "Prototype de serre — vue 1", label: "Galerie — prototype 1" },
          { alt: "Prototype de serre — vue 2", label: "Galerie — prototype 2" },
          { alt: "Prototype de serre — vue 3", label: "Galerie — prototype 3" },
        ],
        diagram: { alt: "Architecture système de la serre connectée", label: "Diagram — architecture système" },
        screenshot: { alt: "Interface Blynk IoT", label: "Screenshot — Blynk interface" },
        video: { alt: "Démonstration du prototype de serre connectée", label: "Video — démonstration du prototype" },
      },
    ],
  },
  marketing: {
    hero: {
      eyebrow: "Digital Marketing",
      title: "Digital Marketing",
      subtitle: "From ideas to digital presence.",
      text: "J'aime comprendre comment un produit trouve son public, comment une entreprise raconte sa valeur et comment une stratégie se transforme en actions concrètes.",
      media: { alt: "Stratégie digitale et marketing", label: "Hero Marketing" },
    },
    journey: {
      title: "Le point de rencontre entre produit, communication et business.",
      paragraphs: [
        "Je ne suis pas arrivé au marketing par un parcours académique classique. Je l'ai découvert sur le terrain, au contact de solutions technologiques et de problématiques business.",
        "J'ai compris qu'une bonne solution ne signifie pas automatiquement que les gens vont la comprendre, l'adopter ou l'acheter. Il faut savoir expliquer, écouter, comprendre le marché, identifier les bonnes personnes et choisir la bonne approche.",
        "C'est ce qui m'a conduit vers le marketing digital, le contenu, le CRM, la prospection et le développement commercial.",
      ],
      emphasis: "Ce qui m'intéresse particulièrement : le point de rencontre entre produit, communication et business.",
      media: { alt: "Parcours marketing de Paul Kombetto", label: "Marketing journey" },
      imageSide: "right",
    },
    caseStudiesTitle: "Case studies",
    caseStudiesIntro: "Montrer le raisonnement, pas seulement les publications : le problème, la stratégie, l'exécution et les leçons apprises.",
    caseStudies: [
      {
        slug: "from-content-to-commercial-action",
        title: "From Content to Commercial Action",
        tagline: "Une expérience à la croisée de la stratégie, du marketing digital, du CRM, de la prospection et du développement commercial.",
        coverMedia: { alt: "De la stratégie de contenu à l'action commerciale", label: "Case study cover" },
        context: "Mon expérience ne s'est pas limitée à produire du contenu. Elle a impliqué la stratégie, le marketing digital, le CRM, la prospection et le développement commercial.",
        challenge: "Ne pas communiquer simplement pour être présent sur les réseaux sociaux, mais faire en sorte que la communication présente mieux les solutions, soutienne les objectifs commerciaux et crée des opportunités.",
        approachSteps: [
          "Comprendre le produit",
          "Identifier la cible",
          "Définir le message",
          "Créer du contenu",
          "Identifier des prospects",
          "Engager la conversation",
          "Assurer le suivi",
        ],
        workDone: ["Content Strategy", "CRM", "Prospecting", "Commercial Development"],
        lesson: "Le marketing et le commercial ne devraient pas être pensés comme deux mondes séparés. Le contenu attire l'attention. La compréhension crée l'intérêt. La relation crée l'opportunité.",
        gallery: [
          { alt: "Contenus et posts", label: "Gallery — posts" },
          { alt: "Outil CRM", label: "Gallery — CRM" },
          { alt: "Prospection commerciale", label: "Gallery — prospection" },
        ],
      },
      {
        slug: "kawa-41devs-campaign",
        title: "KAWA × 41DEVS",
        tagline: "Turning a portfolio of digital solutions into a commercial campaign.",
        coverMedia: { alt: "Campagne commerciale KAWA × 41DEVS", label: "Campaign cover" },
        context: "KAWA et 41DEVS disposent de plusieurs solutions digitales. Le défi n'est pas simplement de présenter des produits, mais de structurer une approche commerciale autour de problèmes réels d'entreprise.",
        challenge: "Cibler des entreprises structurées, avec plusieurs équipes ou processus susceptibles de bénéficier d'une digitalisation — sans commencer par vendre le produit, mais par comprendre le problème.",
        approachSteps: [
          "Market Research",
          "Segmentation",
          "Prospect Identification",
          "Decision-Maker Identification",
          "Personalized Outreach",
          "Follow-up",
          "Opportunity Qualification",
        ],
        workDone: ["Segmentation", "Recherche de prospects", "Identification des décideurs", "Personnalisation du message", "Suivi"],
        lesson: "Une bonne solution présentée à la mauvaise personne, au mauvais moment ou de la mauvaise manière reste une mauvaise approche.",
        gallery: [
          { alt: "Recherche de marché", label: "Gallery — market research" },
          { alt: "Campagne commerciale", label: "Gallery — campagne" },
          { alt: "Supports commerciaux", label: "Gallery — supports" },
        ],
      },
    ],
  },
  leadership: {
    hero: {
      eyebrow: "Leadership & Volunteering",
      title: "Leadership & Volunteering",
      subtitle: "Leadership is not a title. It's what you choose to do when something needs to move.",
      text: "Je m'intéresse à la communication, à la coordination, à la prise de responsabilité et aux initiatives qui permettent aux personnes et aux projets d'avancer ensemble.",
      media: { alt: "Leadership et engagement communautaire", label: "Hero Leadership" },
    },
    journey: {
      title: "Le leadership commence avant le titre.",
      paragraphs: [
        "Quand quelque chose doit être organisé, quand une équipe a besoin d'initiative, quand une idée doit devenir une action ou quand une responsabilité doit être assumée, c'est là que le leadership commence.",
        "Mes expériences m'ont appris à communiquer, écouter, coordonner et prendre des responsabilités.",
        "Mais surtout, elles m'ont appris qu'avancer ne signifie pas tout faire seul. Le leadership, c'est aussi créer les conditions pour que les autres puissent prendre leur place, contribuer et progresser.",
      ],
      media: { alt: "Histoire de leadership de Paul Kombetto", label: "Leadership story" },
      imageSide: "left",
    },
    experiencesTitle: "Experiences",
    experiences: [
      {
        slug: "gavel-club",
        organization: "Toastmasters Gavel Club Ganiatou Sambaou, IFRI-UAC",
        role: "Vice-President of Public Relations",
        period: "Janvier — Octobre 2025",
        title: "Speak. Listen. Adapt. Create space.",
        text: "Préparer et modérer des sessions, organiser des activités et contribuer à la vie du club m'ont appris à structurer mes idées, adapter mon message et créer un espace où les autres peuvent s'exprimer. En tant que Vice-Président des relations publiques, j'ai géré les communications média et coordonné la communication interne et la logistique entre les membres et le bureau exécutif.",
        signature: "Speak clearly. Listen actively. Adapt to the room. Create space for others.",
        media: { alt: "Session du Gavel Club", label: "Gavel Club / session" },
        gallery: [
          { alt: "Session de prise de parole", label: "Gallery — session" },
          { alt: "Événement du club", label: "Gallery — événement" },
          { alt: "Activité de modération", label: "Gallery — activité" },
        ],
      },
    ],
    stories: [
      {
        title: "Taking responsibility",
        situation: "Une équipe avait plusieurs besoins à couvrir avec peu de personnes disponibles.",
        challenge: "Maintenir les activités, contribuer à la structuration et participer à la recherche de nouvelles personnes.",
        action: "J'ai pris plusieurs responsabilités et participé à la recherche et à l'intégration de nouveaux membres.",
        lesson: "Prendre ses responsabilités ne signifie pas tout faire soi-même. Il faut aussi préparer le terrain pour que d'autres puissent prendre leur place.",
        media: { alt: "Prise de responsabilité", label: "Story — taking responsibility" },
      },
      {
        title: "Communication",
        situation: "Une discussion intéressante ne dépend pas uniquement des questions posées.",
        challenge: "Faire en sorte que les participants sentent qu'ils peuvent parler, écouter, questionner et même ne pas être d'accord.",
        action: "La modération m'a appris à créer cet espace : donner une direction sans contrôler chaque intervention.",
        lesson: "Un bon espace de discussion se construit, il ne se décrète pas.",
        media: { alt: "Modération d'une discussion", label: "Story — modération / discussion" },
      },
    ],
    volunteeringTitle: "Volunteering",
    volunteeringIntro: "Le bénévolat est pour moi un espace d'apprentissage autant qu'un espace de contribution. Il permet de travailler avec des profils différents, de servir une communauté et de transformer des idées en initiatives.",
    volunteering: [
      {
        organization: "AIESEC in Benin",
        role: "Partnerships and Youth Engagement Assistant",
        period: "Février 2024 — Janvier 2025",
        contribution: "Direction d'initiatives d'onboarding de partenaires, engageant des organisations pour soutenir des programmes jeunesse, et coordination d'équipes exécutant des projets d'engagement jeunesse dans les communautés locales.",
        learning: "Le développement de partenariats renforce des liens durables avec des parties prenantes externes — une base essentielle pour tout projet à impact.",
        media: { alt: "Engagement bénévole avec AIESEC", label: "Volunteering — AIESEC" },
      },
    ],
  },
  footer: {
    tagline: "Technology × Management × Impact.",
    rights: "Tous droits réservés.",
  },
};

export default fr;
