import type { SiteDictionary } from "@/lib/types";

const en: SiteDictionary = {
  meta: {
    title: "Technology. Digital. Leadership.",
    description:
      "Paul Kombetto's portfolio: an embedded systems and IoT engineer moving into digital, marketing and leadership. Build, connect, move forward.",
  },
  nav: {
    brand: "Paul Kombetto",
    links: [
      { label: "AI & IoT", href: "/ai-iot" },
      { label: "Digital Marketing", href: "/marketing" },
      { label: "Leadership", href: "/leadership" },
      { label: "Contact", href: "/#contact" },
    ],
    languageLabel: "Language",
  },
  profile: {
    name: "Paul Kombetto",
    location: "Cotonou, Benin",
    email: "paulkombetto1@gmail.com",
    phone: "+229 01 63 42 04 44",
    linkedin: "Paul KOMBETTO",
    linkedinUrl: "https://www.linkedin.com/in/paul-kombetto",
  },
  home: {
    hero: {
      eyebrow: "Personal portfolio",
      name: "Paul Kombetto",
      signature: "Technology. Digital. Leadership.",
      headline: "I am building my journey at the intersection of technology, digital and people.",
      media: { alt: "Portrait of Paul Kombetto", label: "Hero — professional portrait" },
      ctas: [
        { label: "Discover my journey", href: "#story" },
        { label: "Get in touch", href: "#contact" },
      ],
    },
    intro: {
      text: "Trained in embedded systems and IoT, I gradually broadened my scope toward digital, project development, communication and leadership. Today, I try to understand problems as a whole, build useful solutions, and help move forward the people and projects that carry them.",
      media: { alt: "Paul Kombetto in his working environment", label: "Intro — journey / working environment" },
    },
    story: {
      eyebrow: "My story",
      title: "I never wanted to limit myself to a single dimension.",
      paragraphs: [
        "My curiosity first led me toward technology. At university, embedded systems and IoT taught me to look at what happens behind applications: sensors, microcontrollers, data, code, and real-world constraints.",
        "But as I moved forward, I realized that good technology is not enough. You also need to understand the problem you're trying to solve, the people affected, their context, and how a solution can actually be adopted.",
        "That's what gradually brought me toward digital, marketing, business development, CRM, project management and leadership.",
      ],
      emphasis: "Build solutions. Understand the stakes. Work with others. And learn to turn ideas into action.",
      media: { alt: "Photo related to Paul's journey", label: "Story — journey photo" },
      imageSide: "right",
    },
    whatIDo: {
      title: "Different fields. One way of thinking.",
      intro: "My experiences may look different at first glance. Yet they rest on the same approach: understand, structure, build and evolve.",
      dimensions: [
        {
          key: "ai-iot",
          keyword: "Build",
          title: "AI & IoT",
          text: "I design and experiment with connected, intelligent systems — at the crossroads of embedded engineering, IoT, automation and AI.",
          href: "/ai-iot",
          media: { alt: "Connected and intelligent systems", label: "AI & IoT card" },
        },
        {
          key: "marketing",
          keyword: "Connect",
          title: "Digital Marketing",
          text: "I work on how products, services and companies explain their value, reach their audience, and turn digital presence into concrete action.",
          href: "/marketing",
          media: { alt: "Digital strategy and marketing", label: "Marketing card" },
        },
        {
          key: "leadership",
          keyword: "Move forward",
          title: "Leadership & Volunteering",
          text: "I'm drawn to communication, coordination, taking responsibility, and the initiatives that let people and projects move forward together.",
          href: "/leadership",
          media: { alt: "Leadership and community engagement", label: "Leadership card" },
        },
      ],
    },
    selectedWork: {
      title: "A few projects that tell my story.",
      items: [
        {
          tag: "AI × IoT × Embedded Systems",
          title: "Smart Automated Greenhouse",
          description: "A connected greenhouse prototype that monitors the environment and automates certain actions.",
          href: "/ai-iot/projects/automated-greenhouse",
          cta: "View project",
          media: { alt: "Automated greenhouse prototype", label: "Project cover — greenhouse" },
        },
        {
          tag: "Marketing × Digital × Business",
          title: "Digital Strategy & Commercial Development",
          description: "Work spanning content strategy, CRM, prospecting and commercial development.",
          href: "/marketing/case-studies/from-content-to-commercial-action",
          cta: "View experience",
          media: { alt: "Digital strategy and commercial development", label: "Marketing work" },
        },
        {
          tag: "Leadership × Communication × Volunteering",
          title: "Leadership & Community",
          description: "Experiences in public speaking, moderation, coordination and community engagement.",
          href: "/leadership",
          cta: "Discover",
          media: { alt: "Community engagement and leadership", label: "Leadership / event" },
        },
      ],
    },
    experience: {
      title: "Learning by doing.",
      entries: [
        {
          organization: "KAWA Services",
          role: "Growth Management Intern",
          period: "July 2026 — Present",
          tags: ["Digital Marketing", "Commercial Development", "Digital Solutions"],
          description: "An experience at the crossroads of marketing, sales and digital solutions, with responsibilities ranging from content strategy to prospecting, CRM and structuring commercial actions.",
          media: { alt: "Working environment at KAWA Services", label: "KAWA — working environment / campaign / solution" },
        },
        {
          organization: "Tout-Talent",
          role: "AI & Tech Applied Growth Intern",
          period: "March — June 2025",
          tags: ["Data", "Growth", "Technical communication"],
          description: "Analyzed user and product data to identify growth and engagement opportunities, translating technical solutions into terms understood by non-technical stakeholders.",
          media: { alt: "Working environment at Tout-Talent", label: "Tout-Talent — working environment" },
        },
        {
          organization: "Benin Excellence",
          role: "Embedded Systems and AI Intern",
          period: "July — August 2024",
          tags: ["Arduino", "Python", "Machine Learning"],
          description: "Prototyped embedded systems with Arduino and Python, from wiring to functional testing, and implemented machine learning algorithms to solve applied engineering problems.",
          media: { alt: "Embedded systems prototyping", label: "Benin Excellence — technical project" },
        },
        {
          organization: "IFRI / University of Abomey-Calavi",
          role: "Bachelor of Science — Embedded Systems & IoT",
          period: "2022 — 2025",
          tags: ["Microcontrollers", "RTOS", "IoT & wireless protocols"],
          description: "A degree that gave me a foundation in embedded systems, programming, electronics, IoT and solution design. Average score: 15.21/20.",
          media: { alt: "University of Abomey-Calavi, IFRI-UAC", label: "University / technical project" },
        },
      ],
    },
    leadershipImpact: {
      title: "Beyond professional titles.",
      paragraphs: [
        "Some experiences don't fit on a résumé line.",
        "Moderating a discussion, speaking up, coordinating an activity, launching an initiative, or taking on a responsibility — these are also situations that shape how you work with others.",
        "These experiences have gradually shaped how I communicate, take initiative, and create an environment where others can contribute too.",
      ],
      media: { alt: "Leadership and community", label: "Leadership / community" },
      imageSide: "left",
    },
    whatsNext: {
      title: "Where I'm going.",
      paragraphs: [
        "My journey is evolving toward a meeting point between technology, management and digital transformation.",
        "I want to keep understanding technology, but also organizations, people, and the factors that let a technology project create real value.",
        "In the long run, I want to contribute to the design, leadership and transformation of technology projects with real impact.",
      ],
      signature: "Technology × Management × Impact.",
      media: { alt: "Future vision and perspectives", label: "Future / vision" },
      imageSide: "right",
    },
    contact: {
      title: "Let's build something useful.",
      text: "An idea, a project, a collaboration, or simply an interesting conversation — I'm always open to discovering new opportunities.",
      media: { alt: "Paul Kombetto — contact", label: "Contact — discreet portrait" },
      emailLabel: "Email",
      phoneLabel: "Phone",
      locationLabel: "Location",
      linkedinLabel: "LinkedIn",
      resumeLabel: "Download my résumé",
    },
  },
  aiIot: {
    hero: {
      eyebrow: "AI & IoT",
      title: "AI & IoT",
      subtitle: "From connected devices to intelligent systems.",
      text: "My technical journey starts with a simple question: how can technology be used to observe, understand and act on the real world?",
      media: { alt: "Connected and intelligent systems", label: "Hero AI & IoT" },
    },
    technicalStory: {
      title: "One thread: perceive, analyze, act.",
      paragraphs: [
        "Embedded systems taught me to look at the physical world behind applications: sensors, microcontrollers, power, communication, data and hardware constraints.",
        "IoT then let me connect that physical world to the digital one.",
        "Then another question appeared: what do you do with all that data? That's where my interest in AI and intelligent systems grew.",
      ],
      emphasis: "I'm drawn to systems that can perceive, analyze and act.",
      media: { alt: "Paul Kombetto's technical journey", label: "Technical journey / diagram" },
      imageSide: "right",
    },
    stats: [
      { label: "Degree", value: "BSc Embedded Systems & IoT" },
      { label: "Languages", value: "Python · C/C++ · Java" },
      { label: "Hands-on", value: "Arduino · ESP32 · Computer Vision" },
    ],
    projectsTitle: "Projects",
    projectsIntro: "Every technical project is told as a story: context, problem, concept, architecture and results.",
    projects: [
      {
        slug: "automated-greenhouse",
        title: "Automated Greenhouse — IoT + AI",
        subtitle: "Smart Automated Greenhouse System",
        category: "AI × IoT × Embedded Systems",
        summary: "A connected greenhouse prototype that monitors the environment and automates certain actions.",
        coverMedia: { alt: "Automated greenhouse prototype", label: "Project cover" },
        context: "Inside a greenhouse, temperature, humidity, light and soil moisture can shift quickly. Manual monitoring takes time and can delay important decisions.",
        problem: "How do you monitor a greenhouse's environment and automatically trigger actions based on the data collected?",
        concept: "Build a connected greenhouse prototype able to collect environmental data and trigger automated actions. This project, completed as my final-year thesis at IFRI-UAC, was motivated by growing up in a farming family — applying low-cost IoT to smallholder agriculture.",
        architectureSteps: ["Sensors", "ESP32", "Data Collection", "Decision / Automation", "Actuators", "Monitoring Interface"],
        hardware: ["ESP32", "DHT11", "Soil Moisture Sensor", "LDR", "Relays"],
        software: ["ESP32 programming (C/C++)", "Blynk IoT", "Automation logic", "Data collection & visualization"],
        role: "System design, component integration, programming, IoT platform connection and automation — as the sole owner of the project, end to end.",
        learnings: [
          "An IoT system is not just a set of connected components.",
          "You need to think through the whole chain: acquisition, communication, processing, decision and action.",
        ],
        futureImprovements: [
          "Improved automation",
          "Advanced data analysis",
          "Adding AI algorithms",
          "Prediction",
          "Energy optimization",
          "Improved architecture",
        ],
        gallery: [
          { alt: "Greenhouse prototype — view 1", label: "Gallery — prototype 1" },
          { alt: "Greenhouse prototype — view 2", label: "Gallery — prototype 2" },
          { alt: "Greenhouse prototype — view 3", label: "Gallery — prototype 3" },
        ],
        diagram: { alt: "System architecture of the connected greenhouse", label: "Diagram — system architecture" },
        screenshot: { alt: "Blynk IoT interface", label: "Screenshot — Blynk interface" },
        video: { alt: "Demonstration of the greenhouse prototype", label: "Video — prototype demonstration" },
      },
    ],
  },
  marketing: {
    hero: {
      eyebrow: "Digital Marketing",
      title: "Digital Marketing",
      subtitle: "From ideas to digital presence.",
      text: "I like understanding how a product finds its audience, how a company tells its value, and how a strategy turns into concrete action.",
      media: { alt: "Digital strategy and marketing", label: "Hero Marketing" },
    },
    journey: {
      title: "The meeting point between product, communication and business.",
      paragraphs: [
        "I didn't come to marketing through a classic academic path. I discovered it on the ground, working with technology solutions and business problems.",
        "I learned that a good solution doesn't automatically mean people will understand it, adopt it, or buy it. You need to explain, listen, understand the market, identify the right people, and choose the right approach.",
        "That's what led me toward digital marketing, content, CRM, prospecting and commercial development.",
      ],
      emphasis: "What interests me most: the meeting point between product, communication and business.",
      media: { alt: "Paul Kombetto's marketing journey", label: "Marketing journey" },
      imageSide: "right",
    },
    caseStudiesTitle: "Case studies",
    caseStudiesIntro: "Showing the reasoning, not just the output: the problem, the strategy, the execution and the lessons learned.",
    caseStudies: [
      {
        slug: "from-content-to-commercial-action",
        title: "From Content to Commercial Action",
        tagline: "An experience at the crossroads of strategy, digital marketing, CRM, prospecting and commercial development.",
        coverMedia: { alt: "From content strategy to commercial action", label: "Case study cover" },
        context: "My work wasn't limited to producing content. It involved strategy, digital marketing, CRM, prospecting and commercial development.",
        challenge: "Not communicating just to be present on social media, but making sure communication better presented the solutions, supported business goals, and created opportunities.",
        approachSteps: [
          "Understand the product",
          "Identify the target",
          "Define the message",
          "Create content",
          "Identify prospects",
          "Start the conversation",
          "Follow up",
        ],
        workDone: ["Content Strategy", "CRM", "Prospecting", "Commercial Development"],
        lesson: "Marketing and sales shouldn't be treated as two separate worlds. Content grabs attention. Understanding builds interest. Relationships create opportunity.",
        gallery: [
          { alt: "Content and posts", label: "Gallery — posts" },
          { alt: "CRM tool", label: "Gallery — CRM" },
          { alt: "Commercial prospecting", label: "Gallery — prospecting" },
        ],
      },
      {
        slug: "kawa-41devs-campaign",
        title: "KAWA × 41DEVS",
        tagline: "Turning a portfolio of digital solutions into a commercial campaign.",
        coverMedia: { alt: "KAWA × 41DEVS commercial campaign", label: "Campaign cover" },
        context: "KAWA and 41DEVS have several digital solutions. The challenge isn't just presenting products — it's structuring a commercial approach around real business problems.",
        challenge: "Target structured companies with several teams or processes that could benefit from digitalization — without starting by selling the product, but by understanding the problem.",
        approachSteps: [
          "Market Research",
          "Segmentation",
          "Prospect Identification",
          "Decision-Maker Identification",
          "Personalized Outreach",
          "Follow-up",
          "Opportunity Qualification",
        ],
        workDone: ["Segmentation", "Prospect research", "Decision-maker identification", "Message personalization", "Follow-up"],
        lesson: "A good solution presented to the wrong person, at the wrong time, or in the wrong way, is still a bad approach.",
        gallery: [
          { alt: "Market research", label: "Gallery — market research" },
          { alt: "Commercial campaign", label: "Gallery — campaign" },
          { alt: "Sales materials", label: "Gallery — materials" },
        ],
      },
    ],
  },
  leadership: {
    hero: {
      eyebrow: "Leadership & Volunteering",
      title: "Leadership & Volunteering",
      subtitle: "Leadership is not a title. It's what you choose to do when something needs to move.",
      text: "I'm drawn to communication, coordination, taking responsibility, and the initiatives that let people and projects move forward together.",
      media: { alt: "Leadership and community engagement", label: "Hero Leadership" },
    },
    journey: {
      title: "Leadership starts before the title.",
      paragraphs: [
        "When something needs organizing, when a team needs initiative, when an idea needs to become action, or when a responsibility needs to be taken on — that's where leadership begins.",
        "My experiences taught me to communicate, listen, coordinate and take on responsibility.",
        "But above all, they taught me that moving forward doesn't mean doing everything alone. Leadership is also about creating the conditions for others to take their place, contribute, and grow.",
      ],
      media: { alt: "Paul Kombetto's leadership story", label: "Leadership story" },
      imageSide: "left",
    },
    experiencesTitle: "Experiences",
    experiences: [
      {
        slug: "gavel-club",
        organization: "Toastmasters Gavel Club Ganiatou Sambaou, IFRI-UAC",
        role: "Vice-President of Public Relations",
        period: "January — October 2025",
        title: "Speak. Listen. Adapt. Create space.",
        text: "Preparing and moderating sessions, organizing activities and contributing to club life taught me to structure my ideas, adapt my message, and create a space where others can express themselves. As Vice-President of Public Relations, I managed media communications and coordinated internal communication and logistics between members and the executive office.",
        signature: "Speak clearly. Listen actively. Adapt to the room. Create space for others.",
        media: { alt: "Gavel Club session", label: "Gavel Club / session" },
        gallery: [
          { alt: "Public speaking session", label: "Gallery — session" },
          { alt: "Club event", label: "Gallery — event" },
          { alt: "Moderation activity", label: "Gallery — activity" },
        ],
      },
    ],
    stories: [
      {
        title: "Taking responsibility",
        situation: "A team had several needs to cover with few people available.",
        challenge: "Keeping activities running, contributing to structuring the team, and helping find new people.",
        action: "I took on several responsibilities and helped recruit and onboard new members.",
        lesson: "Taking responsibility doesn't mean doing everything yourself. You also have to prepare the ground so others can take their place.",
        media: { alt: "Taking on responsibility", label: "Story — taking responsibility" },
      },
      {
        title: "Communication",
        situation: "An interesting discussion doesn't depend only on the questions asked.",
        challenge: "Making sure participants feel they can speak, listen, question, and even disagree.",
        action: "Moderation taught me to create that space: giving direction without controlling every intervention.",
        lesson: "A good space for discussion is built, not declared.",
        media: { alt: "Moderating a discussion", label: "Story — moderation / discussion" },
      },
    ],
    volunteeringTitle: "Volunteering",
    volunteeringIntro: "Volunteering is, for me, as much a space to learn as a space to contribute. It means working with different profiles, serving a community, and turning ideas into initiatives.",
    volunteering: [
      {
        organization: "AIESEC in Benin",
        role: "Partnerships and Youth Engagement Assistant",
        period: "February 2024 — January 2025",
        contribution: "Led partner onboarding initiatives, engaging organizations to support youth programs, and coordinated teams executing youth engagement projects across local communities.",
        learning: "Building partnerships strengthens lasting ties with external stakeholders — an essential foundation for any project with real impact.",
        media: { alt: "Volunteering with AIESEC", label: "Volunteering — AIESEC" },
      },
    ],
  },
  footer: {
    tagline: "Technology × Management × Impact.",
    rights: "All rights reserved.",
  },
};

export default en;
